class Nation {
  final int id;
  final String name;
  String flag;

  Nation(this.id, this.name);

  static List<Nation> nationList() {
    return <Nation>[
      Nation(1, 'Việt Nam'),
      Nation(2, 'Lao'),
      Nation(3, 'Cambodia'),
      Nation(4, 'Andorra'),
      Nation(5, 'United Arab Emirates'),
      Nation(6, 'Afghanistan'),
      Nation(7, 'Antigua and Barbuda'),
      Nation(8, 'Anguilla'),
      Nation(9, 'Albania'),
      Nation(10, 'Armenia'),
      Nation(11, 'Angola'),
      Nation(12, 'Antarctica'),
      Nation(13, 'Argentina'),
      Nation(14, 'American Samoa'),
      Nation(15, 'Austria'),
      Nation(16, 'Australia '),
      Nation(17, 'Aruba'),
      Nation(18, 'Aland Islands'),
      Nation(19, 'Azerbaijan'),
      Nation(20, 'Bosnia and Herzegovina'),
      Nation(21, 'Barbados'),
      Nation(22, 'Bangladesh'),
      Nation(23, 'Belgium'),
      Nation(24, 'Burkina Faso'),
      Nation(25, 'Bulgaria'),
      Nation(26, 'Bahrain'),
      Nation(27, 'Burundi'),
      Nation(28, 'Benin'),
      Nation(29, 'Saint Barthalemy'),
      Nation(30, 'Bermuda'),
      Nation(31, 'Brunei Darussalam'),
      Nation(32, 'Bolivia'),
      Nation(33, 'Bonaire'),
      Nation(34, 'Brazil'),
      Nation(35, 'Bahamas'),
      Nation(36, 'Bhutan'),
      Nation(37, 'Bouvet Island'),
      Nation(38, 'Botswana'),
      Nation(39, 'Belarus'),
      Nation(40, 'Belize'),
      Nation(41, 'Canada'),
      Nation(42, 'Cocos (Keeling) Islands'),
      Nation(43, 'Democratic Republic of the Congo'),
      Nation(44, 'Central African Republic'),
      Nation(45, 'Congo'),
      Nation(46, 'Switzerland'),
      Nation(47, 'CÃ´te dIvoire'),
      Nation(48, 'Cook Islands'),
      Nation(49, 'Chile'),
      Nation(50, 'Cameroon'),
      Nation(51, 'China'),
      Nation(52, 'Colombia'),
      Nation(53, 'Costa Rica'),
      Nation(54, 'Cuba'),
      Nation(55, 'Cape Verde'),
      Nation(56, 'CuraÃ§ao'),
      Nation(57, 'Christmas Island'),
      Nation(58, 'Cyprus'),
      Nation(59, 'Czech Republic'),
      Nation(60, 'Germany'),
      Nation(61, 'Djibouti'),
      Nation(62, 'Denmark'),
      Nation(63, 'Dominica'),
      Nation(64, 'Dominican Republic'),
      Nation(65, 'Algeria'),
      Nation(66, 'Ecuador'),
      Nation(67, 'Estonia'),
      Nation(68, 'Egypt'),
      Nation(69, 'Western Sahara'),
      Nation(70, 'Eritrea'),
      Nation(71, 'Spain'),
      Nation(72, 'Ethiopia'),
      Nation(73, 'Finland'),
      Nation(74, 'Fiji'),
      Nation(75, 'Falkland Islands (Malvinas)'),
      Nation(76, 'Micronesia, Federated States of'),
      Nation(77, 'Faroe Islands'),
      Nation(78, 'France'),
      Nation(79, 'Gabon'),
      Nation(80, 'Great Britain'),
      Nation(81, 'Grenada'),
      Nation(82, 'Georgia'),
      Nation(83, 'French Guiana'),
      Nation(84, 'Guernsey'),
      Nation(85, 'Ghana'),
      Nation(86, 'Gibraltar'),
      Nation(87, 'Greenland'),
      Nation(88, 'Gambia'),
      Nation(89, 'Guinea'),
      Nation(90, 'Guadeloupe'),
      Nation(91, 'Equatorial Guinea'),
      Nation(92, 'Greek'),
      Nation(93, 'South Georgia and the South Sandwich Islands'),
      Nation(94, 'Guatemala'),
      Nation(95, 'Guam'),
      Nation(96, 'Guinea-Bissau'),
      Nation(97, 'Guyana'),
      Nation(98, 'Hong Kong'),
      Nation(99, 'Heard Island and McDonald Mcdonald Islands'),
      Nation(100, 'Honduras'),
      Nation(101, 'Croatia'),
      Nation(102, 'Haiti'),
      Nation(103, 'Hungary'),
      Nation(104, 'Indonesia'),
      Nation(105, 'Ireland'),
      Nation(106, 'Israel'),
      Nation(107, 'Isle of Man'),
      Nation(108, 'Indian'),
      Nation(109, 'British Indian Ocean Territory'),
      Nation(110, 'Iraq'),
      Nation(111, 'Iran, Islamic Republic of'),
      Nation(112, 'Iceland'),
      Nation(113, 'Italia'),
      Nation(114, 'Jersey'),
      Nation(115, 'Jamaica'),
      Nation(116, 'Jordan'),
      Nation(117, 'Japan'),
      Nation(118, 'Kenya'),
      Nation(119, 'Kyrgyzstan'),
      Nation(120, 'Kiribati'),
      Nation(121, 'Comoros'),
      Nation(122, 'Saint Kitts and Nevis'),
      Nation(123, 'North Korea'),
      Nation(124, 'Korea'),
      Nation(125, 'Kuwait'),
      Nation(126, 'Cayman Islands'),
      Nation(127, 'Kazakhstan'),
      Nation(128, 'Lao Peoples Democratic Republic'),
      Nation(129, 'Lebanon'),
      Nation(130, 'Saint Lucia'),
      Nation(131, 'Liechtenstein'),
      Nation(132, 'Sri Lanka'),
      Nation(133, 'Liberia'),
      Nation(134, 'Lesotho'),
      Nation(135, 'Lithuania'),
      Nation(136, 'Luxembourg'),
      Nation(137, 'Latvia'),
      Nation(138, 'Libya'),
      Nation(139, 'Morocco'),
      Nation(140, 'Monaco'),
      Nation(141, 'Moldova, Republic of'),
      Nation(142, 'Montenegro'),
      Nation(143, 'Saint Martin (French part)'),
      Nation(144, 'Madagascar'),
      Nation(145, 'Marshall Islands'),
      Nation(146, 'Macedonia, the Former Yugoslav Republic of'),
      Nation(147, 'Mali'),
      Nation(148, 'Myanmar'),
      Nation(149, 'Mongolia'),
      Nation(150, 'Macao'),
      Nation(151, 'Northern Mariana Islands'),
      Nation(152, 'Martinique'),
      Nation(153, 'Mauritania'),
      Nation(154, 'Montserrat'),
      Nation(155, 'Malta'),
      Nation(156, 'Mauritius'),
      Nation(157, 'Maldives'),
      Nation(158, 'Malawi'),
      Nation(159, 'Mexico'),
      Nation(160, 'Malaysia'),
      Nation(161, 'Mozambique'),
      Nation(162, 'Namibia'),
      Nation(163, 'New Caledonia'),
      Nation(164, 'Niger'),
      Nation(165, 'Norfolk Island'),
      Nation(166, 'Nigeria'),
      Nation(167, 'Nicaragua'),
      Nation(168, 'Netherlands'),
      Nation(169, 'Norway'),
      Nation(170, 'Nepal'),
      Nation(171, 'Nauru'),
      Nation(172, 'Niue'),
      Nation(173, 'New Zealand'),
      Nation(174, 'Oman'),
      Nation(175, 'Panama'),
      Nation(176, 'Peru'),
      Nation(177, 'French Polynesia'),
      Nation(178, 'Papua New Guinea'),
      Nation(179, 'Philippines'),
      Nation(180, 'Pakistan'),
      Nation(181, 'Poland'),
      Nation(182, 'Saint Pierre and Miquelon'),
      Nation(183, 'Pitcairn'),
      Nation(184, 'Puerto Rico'),
      Nation(185, 'Palestine, State of'),
      Nation(186, 'Portugal'),
      Nation(187, 'Palau'),
      Nation(188, 'Paraquay'),
      Nation(189, 'Qatar'),
      Nation(190, 'Reunion'),
      Nation(191, 'Rumani'),
      Nation(192, 'Serbia'),
      Nation(193, 'Russian'),
      Nation(194, 'Rwanda'),
      Nation(195, 'Saudi Arabia'),
      Nation(196, 'Solomon Islands'),
      Nation(197, 'Seychelles'),
      Nation(198, 'Sudan'),
      Nation(199, 'Sweden'),
      Nation(200, 'Singapore'),
      Nation(201, 'Saint Helena'),
      Nation(202, 'Slovenia'),
      Nation(203, 'Svalbard and Jan Mayen'),
      Nation(204, 'Slovakia'),
      Nation(205, 'Sierra Leone'),
      Nation(206, 'San Marino'),
      Nation(207, 'Senegal'),
      Nation(208, 'Somalia'),
      Nation(209, 'Suriname'),
      Nation(210, 'South Sudan'),
      Nation(211, 'Sao Tome and Principe'),
      Nation(212, 'El Salvador'),
      Nation(213, 'Sint Maarten (Dutch part)'),
      Nation(214, 'Syrian Arab Republic'),
      Nation(215, 'Swaziland'),
      Nation(216, 'Turks and Caicos Islands'),
      Nation(217, 'Chad'),
      Nation(218, 'French Southern Territories'),
      Nation(219, 'Togo'),
      Nation(220, 'Thailand'),
      Nation(221, 'Tajikistan'),
      Nation(222, 'Tokelau'),
      Nation(223, 'Timor-Leste'),
      Nation(224, 'Turkmenistan'),
      Nation(225, 'Tunisia'),
      Nation(226, 'Tonga'),
      Nation(227, 'Turkey'),
      Nation(228, 'Trinidad and Tobago'),
      Nation(229, 'Tuvalu'),
      Nation(230, 'Taiwan'),
      Nation(231, 'United Republic of Tanzania'),
      Nation(232, 'Ucraina'),
      Nation(233, 'Uganda'),
      Nation(234, 'United States Minor Outlying Islands'),
      Nation(235, 'United States'),
      Nation(236, 'Uruquay'),
      Nation(237, 'Uzbekistan'),
      Nation(238, 'Holy See (Vatican City State)'),
      Nation(239, 'Saint Vincent and the Grenadines'),
      Nation(240, 'Venezuela'),
      Nation(241, 'British Virgin Islands'),
      Nation(242, 'US Virgin Islands'),
      Nation(243, 'Vanuatu'),
      Nation(244, 'Wallis and Futuna'),
      Nation(245, 'Samoa'),
      Nation(246, 'Yemen'),
      Nation(247, 'Mayotte'),
      Nation(248, 'South Africa'),
      Nation(249, 'Zambia'),
      Nation(250, 'Zimbabwe'),

    ];
  }
}
